export const SET_CURRENT_PART = "SET_CURRENT_PART";
export const TOGGLE_RANDOM = "TOGGLE_RANDOM";
export const TOGGLE_REPEAT = "TOGGLE_OPTIONS";
export const TOGGLE_PLAYING = "TOGGLE_PLAYING";
export const SET_PARTS_ARRAY = "SET_PARTS_ARRAY";
